import { OperationEvent } from '../types';

export const MOCK_EVENTS: OperationEvent[] = [
  {
    id: '1',
    title: '双十一大促',
    description: '全站双十一促销活动，折扣力度最大',
    startDate: '2026-11-01',
    endDate: '2026-11-11',
    type: 'promotion',
    status: 'planned',
    owner: '张三',
    tags: ['大促', '全站'],
  },
  {
    id: '2',
    title: '新品春季系列上线',
    description: '春季新品正式上架，同步开启预售',
    startDate: '2026-03-01',
    endDate: '2026-03-05',
    type: 'launch',
    status: 'ongoing',
    owner: '李四',
    tags: ['新品', '春季'],
  },
  {
    id: '3',
    title: '数据库例行维护',
    description: '凌晨2点到4点数据库例行维护，服务暂停',
    startDate: '2026-03-10',
    endDate: '2026-03-10',
    type: 'maintenance',
    status: 'planned',
    owner: '王五',
    tags: ['维护', '数据库'],
  },
  {
    id: '4',
    title: '品牌营销活动',
    description: '社交媒体品牌推广活动',
    startDate: '2026-03-15',
    endDate: '2026-03-20',
    type: 'campaign',
    status: 'planned',
    owner: '赵六',
    tags: ['品牌', '社媒'],
  },
  {
    id: '5',
    title: '季度运营复盘会议',
    description: 'Q1运营数据总结与Q2规划讨论',
    startDate: '2026-03-28',
    endDate: '2026-03-28',
    type: 'meeting',
    status: 'planned',
    owner: '张三',
    tags: ['复盘', 'Q1'],
  },
  {
    id: '6',
    title: '五一劳动节促销',
    description: '劳动节期间全场8折优惠',
    startDate: '2026-04-30',
    endDate: '2026-05-05',
    type: 'promotion',
    status: 'planned',
    owner: '李四',
    tags: ['假日', '促销'],
  },
];
